### ISSUE TITLE
2.2 Example: JWT and "that segment"

### ISSUE THREAD

**Issue by brianraymor** [webpush-wg/webpush-vapid#12]
```
Issue: The first part of the JWT is effectively fixed. Would be it
acceptable to require that that segment is omitted from the header
field?
```

What is "that segment"?

**Comment by jrconlin** [comment]
Optimizations, like dropping the header segment, tend to be problematic for some implementers, particularly since the final signature is derived from the first two segments. Also, dropping the header segment prevents possible future changes for encryption types, versioning, or other potentially required items.

**Comment by brianraymor** [comment]
Agreed. I was requesting clarification because it was unclear what omission was being proposed. For example, if it was the header, then that would be a problem  because [RFC7515](https://tools.ietf.org/html/rfc7515#section-4.1.1) states that the alg parameter _MUST be present and MUST be understood and processed by implementations._

**Comment by martinthomson** [comment]
I'll confirm with the list, but @jrconlin is right here.  We can pay a little extra here.  It will mean that there is some possibility of variation in the header (whitespace), but we know how to do that.
